### ISSUE TITLE
Some issues as reported by @mdasoh

### ISSUE THREAD

**Issue by tkchia** [tkchia/GW-BASIC#1]
From https://github.com/dspinellis/GW-BASIC/issues/6#issuecomment-638869472 :
> [@mdasoh:]

> tkchia, I just went to your repository this morning and cloned and compiled with jwasm/jwlink (very convenient!) and encountered the following issues with your (largely working!) gwbasic.exe:
> ```
> 1) cannot scroll from the bottom of the screen
> 2) pressing F9 KEY for example offers no " " after it
> 3) TIMER ON and TIMER OFF aren't there
> 4) SHELL isn't there
> 5) pressing the INS button doesn't enter insert mode
> 6) pressing the DEL or BS buttons deletes from the end of the line, not from here
> 7) listing my program, I may get spaces after each line, or incomplete length
>  - with this, it may be related to not scrolling properly

> all in all I'm glad to see gwbasic working so well! here is the code I tested with:

> ```
> 1 X$ = ""
> 2 GOTO 10
> 5 STOP
> 6 CLS
> 7 PRINT TIME$"] "X$;
> 8 RETURN
> 10 CLS
> 30 ON TIMER( 3 ) GOSUB 6
> 33 TIMER ON
> 36 CLS
> 40 PRINT TIME$"] "X$;
> 41 Y$ = INKEY$
> 42 IF LEN( Y$ ) = 0 THEN GOTO 41
> 48 X$ = X$ + Y$
> 50 IF Y$=CHR$(27) THEN GOTO 5
> 52 IF Y$=CHR$(8) THEN GOSUB 92
> 53 IF Y$<>CHR$(13) THEN GOTO 36
> 60 PRINT "  [working]"
> 62 TIMER OFF
> 70 SHELL X$
> 72 X$ = ""
> 75 LOCATE 24, 1
> 78 PRINT "taco. . .";
> 80 Y$ = INPUT$( 1 )
> 90 GOTO 10
> 92 WELL = LEN( X$ )
> 93 IF WELL < 2 THEN RETURN
> 94 X$ = LEFT$( X$, WELL - 2 )
> 95 RETURN
> ```

**Comment by tkchia** [comment]
Hello @mdasoh,

Thank you for your feedback.
> `1) cannot scroll from the bottom of the screen`
...
> `5) pressing the INS button doesn't enter insert mode`
> `6) pressing the DEL or BS buttons deletes from the end of the line, not from here`
> `7) listing my program, I may get spaces after each line, or incomplete length`
> ` - with this, it may be related to not scrolling properly`

I have not encountered these problems while testing under DOSBox.  Which particular 8086 emulator (or 8086 machine) are you using?

> `2) pressing F9 KEY for example offers no " " after it`
> `3) TIMER ON and TIMER OFF aren't there`
> `4) SHELL isn't there`

Hmm, these seem to be problems that stem from the original source code as released by Microsoft.

On F9:
  * `GWRAM.ASM` defines F9 to expand to `KEY` with no trailing space.  Yes, this is different from the behaviour for more recent versions of GW-BASIC (e.g. version 3.23 from 1988).
  * Another difference I found is that the padding after each function key display appears in reverse video, e.g. `RUN←␣␣`.  (In later GW-BASICs, only the characters which are part of the function key expansion, i.e. `RUN←`, appear in reverse video.)
  * These can probably be changed --- by changing the 1983 source code --- although I am not sure at the moment if it will be good to change these.

On `TIMER` and `SHELL`: these are apparently not supported at all in this version of GW-BASIC (see `GWSTS.ASM`).

Thank you!

**Comment by dmsc** [comment]
Hi @tkchia!

I found an older version of GW-BASIC that is similar to the released sources: from WinWorldPC you can download the MS-DOS 1.25  Compaq OEM rev 1.10 files: https://winworldpc.com/download/50b03da1-9069-11e9-ab10-fa163e9022f0

Inside, you would find a BASICA.EXE file, md5sum 0e65e58ebca2c6bfb431f73dbedf8568, which reports version 1.12:

![image](https://user-images.githubusercontent.com/5713395/83879570-d6e48200-a70b-11ea-9551-bcc415119f8b.png)

This version does not put the space after "KEY" on F9, and seems very similar to the one from the sources.

Note that in the next version available from WinWorldPC, MS-DOS 1.25, Compaq OEM rev 1.11, the BASIC.EXE file reports version 1.13 and already has the "KEY" with space on F9.

Overall, from WinWorldPC you can extract the following old versions:

Size | MD5 | File
------|-----|------
53760 | 0e65e58ebca2c6bfb431f73dbedf8568 | basica-1.12-compaq.exe
54272 | 28e22caa7ec534a78d37aa3314690758 | basica-1.13-compaq.exe                       
54304 | 493812edd5f7826a3e027f7b3b62b831 | basica-1.14-compaq.exe
64272 | 61f23252015faad97f63c1d0609e3476 | basica-2.11-compaq.exe

**Comment by mdasoh** [comment]
I'm using pcem, with mda.rom and both 09may86 ibmxt roms from http://www.elpod.org/pcem_roms/ and sources from https://bitbucket.org/pcem_emulator/pcem/downloads/ compiled with debian 32bit.

**Comment by tkchia** [comment]
Hello @mdasoh,

Thank you for the information.

I still have a bit of trouble setting up PCem --- but I just found a bug in my screen scrolling code for the monochrome text mode.  It should be fixed now (https://github.com/tkchia/GW-BASIC/commit/3f05fcbf412369ab51f60cb2e19a31c1d528a92b).

Let me know if the updated version works for you.

Thank you!

**Comment by mdasoh** [comment]
It is scrolling properly and I am no longer experiencing the (relevant) above issues, however the cursor does not change to reflect insert mode.

**Comment by tkchia** [comment]
Hello @mdasoh,

Thanks for your feedback.  I have not yet written the code to change the cursor shape; I hope to do that soon.

Thank you!

**Comment by tkchia** [comment]
Hello @dmsc,

Indeed, the COMPAQ BASIC 1.12 binary looks like it might be of interest. :-)  Still, to be on the safe side for the time being, I think I will continue to see how much mileage I can get out of the `BASICA.COM` binary distributed with the MS-DOS source code...

Thank you!

**Comment by tkchia** [comment]
Hello @mdasoh,

> It is scrolling properly and I am no longer experiencing the (relevant) above issues, however the cursor does not change to reflect insert mode.

I have added some code to change cursor shapes (https://github.com/tkchia/GW-BASIC/commit/e46db64ff24bfc16cc1d92448ffcbf0f087b513b).  You should be able to see an "insert mode" cursor now.  Thank you!

**Comment by tkchia** [comment]
Hello @mdasoh,

Let me know if it is OK with you to close this issue.  Thank you!

**Comment by buricco** [comment]
Compaq's GW-BASIC was built with a switch that enabled bug-compatibility with IBM's version.  Until 3.2, the standard build had some differences from IBM - and with 3.2, they attempted to make the standard build as bug-compatible as possible with IBM's.

**Comment by mdasoh** [comment]
Yes @tkchia you can close this, it is no longer an issue.
