### ISSUE TITLE
jwasm incompatibilities

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [tkchia/GW-BASIC#5]
>	 For some reason JWasm does not insert needed CS: segment overrides
>	 for these.  Urrrgh.  (I have reported this issue at
>	 https://github.com/JWasm/JWasm/issues/211 .)

jwasm development by me (japheth) is continued on https://github.com/Baron-von-Riedesel/JWasm

The error mentioned above has been fixed in the newest prerelease:
https://github.com/Baron-von-Riedesel/JWasm/blob/master/bin/JWasm_v214pre3_win32.zip

**Comment by tkchia** [comment]
Hello @Baron-von-Riedesel ,

Thank you for the fix!  I will update my GW-BASIC build scripts to use your version.

**Comment by tkchia** [comment]
Hello @Baron-von-Riedesel ,

It seems that GW-BASIC fails --- in a different way though --- when I assemble it with your updated assembler.  I will need to hold the update, at least until I figure out what is going on.  Thanks again!

**Comment by tkchia** [comment]
Hello @Baron-von-Riedesel ,

It seems that the updated assembler now has an opposite problem: a simple `LODSB`, `LODSW`, `MOVSB`, `MOVSW`, `CMPSB`, or `CMPSW` may sometimes stuff a random segment override (`CS:` or `ES:`) when there should not be one.  I will submit an issue report for this.

Thank you!

**Comment by tkchia** [comment]
Hello @Baron-von-Riedesel ,

Thanks for your second bug fix!

I have modified my build scripts accordingly (https://github.com/tkchia/GW-BASIC/commit/7e7cd695ce24b8415427050e7f760ebb4bdd6913) to switch to your JWasm.

(However, I am not able to use your version of JWlink yet, as it does not seem to support a Unix host.)

Thank you!
