### ISSUE TITLE
Unable to stop running program

### ISSUE THREAD

**Issue by rlauzon54** [tkchia/GW-BASIC#9]
Hardware: An older Pentium system running FreeDOS.

Test program
```
10 A$=INKEY$
20 IF A$="q" THEN END
30 GOTO 30
```

No key combination will break into the program execution.  I added line 20 so that I could stop the program.

I should be able to do something (like Control-C) to halt program execution.

**Comment by tkchia** [comment]
Hello @rlauzon54,

Not exactly a bug, since it seems that e.g. COMPAQ BASIC 1.12 behaves similarly.

But I am guessing that older BASICs might recognize a Ctrl-Break key combination, at least for those keyboards that actually have a physical "Break" key.  Perhaps it might be good to make the new `GWBASICA.EXE` (and perhaps `GWBASIC.EXE`) recognize some other key combination as if it is Ctrl-Break.

Thank you!

**Comment by tkchia** [comment]
Hello @rlauzon54, hello @KylinGuo,

I added a patch (https://github.com/tkchia/GW-BASIC/commit/7cc9baeb5462275771e48e7789868aaaf79f40e2) to get `GWBASIC.EXE` to handle the Ctrl-Break key combination, which should work if your keyboard has a "Break" (or "Pause") key (see https://en.wikipedia.org/wiki/Break_key).

For keyboards which lack such a key, again, I hope to get something working for those.

(Meanwhile, if you are running` GWBASIC.EXE` or `GWBASICA.EXE` under QEMU, you can run the QEMU monitor command
```
sendkey ctrl-pause
```
to send a Ctrl-Break key combination to the VM.  You should be able to access the QEMU monitor screen through QEMU's user interface menus.  I am not sure if DOSBox offers such a feature.)

Thank you!

**Comment by geneb** [comment]
On Mon, 12 Dec 2022, tkchia wrote:

> Hello @rlauzon54, hello @KylinGuo,
>
> I added a patch (https://github.com/tkchia/GW-BASIC/commit/7cc9baeb5462275771e48e7789868aaaf79f40e2) to get `GWBASIC.EXE` to handle the Ctrl-Break key combination, which should work if your keyboard has a "Break" (or "Pause") key (see https://en.wikipedia.org/wiki/Break_key).
>
> For keyboards which lack such a key, again, I hope to get something working for those.
>

Control-C should also work for breaking a running program.  I don't have a 
system set up with GWBASIC on it, my my memory tells me both ^C and ^BREAK 
did the same thing.

g.

-- 
Proud owner of F-15C 80-0007
http://www.f15sim.com - The only one of its kind.
http://www.diy-cockpits.org/coll - Go Collimated or Go Home.
Some people collect things for a hobby.  Geeks collect hobbies.

ScarletDME - The red hot Data Management Environment
A Multi-Value database for the masses, not the classes.
http://scarlet.deltasoft.com - Get it _today_!

**Comment by rlauzon54** [comment]
> Control-C should also work for breaking a running program. I don't have a system set up with GWBASIC on it, my my memory tells me both ^C and ^BREAK did the same thing. g.

Testing GWBASIC 1.??, Control-C worked to break out of a running program.

I also tested GWBASIC 3.23.  Control-C does **not** work, but control-Scroll lock (which is where the Break key is on one of my vintage MS-DOS systems) does.

**Comment by tkchia** [comment]
Hello @rlauzon54 and friends,

I added another patch (https://github.com/tkchia/GW-BASIC/commit/231fa584d5c2f184bf6a4aa5c87c6dfe3878609f) to recognize a new key combination, Ctrl-Shift-B, and make it emulate a Ctrl-Break.  This should work if your keyboard happens to lack Break / Pause / Scroll Lock keys.

Thank you!

**Comment by tkchia** [comment]
The interpreter now also (https://github.com/tkchia/GW-BASIC/commit/2ccf2b3ea5381681bb6f7a7aff0bd6e38bdc7ea9) recognizes a Ctrl-Shift-P key combination.  This emulates a Pause or Ctrl-NumLock key combination.

Thank you!
